version: '3'
services:
    42docker:
        build: .
        environment: 
            - INTRA=nervin
        volumes: 
            - ./42git:/home/${INTRA}/42git
        stdin_open: true
        tty: true
